Ingredient.create(name: "Rum")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Coca-Cola")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Heavy cream")
Ingredient.create(name: "Kaluah")
Ingredient.create(name: "Lemon")
Ingredient.create(name: "Club soda")
Ingredient.create(name: "Mint Leaves")
Ingredient.create(name: "Whiskey")
